version: "2"
services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: "dvdrental"
        POSTGRES_PASSWORD: "password"
        POSTGRES_USER: "postgres"
    restart: always

  postgrest:
    container_name: postgrest 
    image: postgrest/postgrest
    ports:
        - "3000:3000"
    links:
        - postgres:postgres
    environment:
            PGRST_DB_URI: postgres://postgres:password@postgres:5432/dvdrental
            PGRST_DB_SCHEMA: public
            PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
    depends_on:
        - postgres
    restart: always

  postgui:
    container_name: postgui
    stdin_open: true
    image: davarski/postgui:1.0
    ports:
        - "8771:8771"
    restart: always
    depends_on:
        - postgres
        - postgrest

