apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: postgui
  name: postgui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: postgui
    spec:
      containers:
        - image: davarski/postgui:1.0
          name: postgui
          ports:
            - containerPort: 8771
          resources: {}
          stdin: true
      restartPolicy: Always
status: {}
