apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: postgrest
  name: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgrest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: postgrest
    spec:
      containers:
        - env:
            - name: PGRST_DB_ANON_ROLE
              value: postgres
            - name: PGRST_DB_SCHEMA
              value: public
            - name: PGRST_DB_URI
              value: postgres://postgres:password@postgres:5432/dvdrental
          image: postgrest/postgrest
          name: postgrest
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
