apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: postgui
  name: postgui
spec:
  ports:
    - name: "8771"
      port: 8771
      targetPort: 8771
  selector:
    io.kompose.service: postgui
status:
  loadBalancer: {}
